### ISSUE TITLE
goodtg: command not found

### ISSUE THREAD

**Issue by ZhaoningYu1996** [divelab/LECI#1]
Hi,

I create a virtual environment using environment.yml.
However, when I am running `goodtg --config_path final_configs/GOODHIV/scaffold/covaraite/LECI.yaml`
It shows `goodtg: command not found`

Could you help me with it?
Thank you!

**Comment by CM-BF** [comment]
Hi Zhaoning,

Thank you for asking! To use the command `goodtg`, you have to install the project as a package by executing `pip install -e .` under the project root folder where you can find the file `setup.py`. If you don't want to install the project, you could replace `goodtg` with `python -m GOOD.kernel.main` to run the code. Hope that helps.

Best regards,
Shurui Gui

**Comment by ZhaoningYu1996** [comment]
Thank you for your help!
