### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by depcco** [divelab/LECI#2]

**Comment by depcco** [comment]
I PUT DATASET IN storage/datasets
look like is all right but no outcome。Can you tell me why。thank you


<img width="999" alt="1715048000944" src="https://github.com/divelab/LECI/assets/169051868/85e29ac9-7807-4ce5-ab8e-09d450784303">
<img width="714" alt="1715048122157" src="https://github.com/divelab/LECI/assets/169051868/eb99345f-4ba7-4ad7-ae5a-99dde2446c30">

**Comment by depcco** [comment]
I PUT DATASET IN storage/datasets
look like is all right but no outcome。Can you tell me why。thank you
![image](https://github.com/divelab/LECI/assets/169051868/ae40c878-8e77-4d0c-9719-b2f06516caf3)
![image](https://github.com/divelab/LECI/assets/169051868/f62c3fed-93b6-4533-bc5c-8b9f817657f7)
![image](https://github.com/divelab/LECI/assets/169051868/8a975203-558e-4215-a5b5-ae05419879ff)

**Comment by depcco** [comment]
do you know to Can you tell me how to fix this error。thank you

<img width="1136" alt="1715088550318" src="https://github.com/divelab/LECI/assets/169051868/94a16845-a70d-4cf5-a05f-eebf73ecc4bc">
<img width="333" alt="1715088619718" src="https://github.com/divelab/LECI/assets/169051868/936611c2-8b7c-4cee-aaef-1de3f549f040">

**Comment by CM-BF** [comment]
Hi @depcco,

My guess is that the error comes from `cilog`, but I am afraid that the information provided is not enough to locate the problem. 

Many issues could come from the installation. You may try to reinstall the conda environment adherent to the `environment.yml`, or you may follow the [dependency installation instruction](https://github.com/divelab/GOOD?tab=readme-ov-file#installation) in GOOD.

Best

**Comment by depcco** [comment]
I have located an error through debugging. There is a problem with the pbar code in basic_pipeline. Do you know how to modify it? Translate this sentence
![image](https://github.com/divelab/LECI/assets/169051868/f70e3c81-e422-4862-a179-a8e39a7b8630)

**Comment by CM-BF** [comment]
Okay, maybe your console does not support the setting we set, then you can simply remove the `**pbar_setting`.

**Comment by depcco** [comment]
The problem remains unresolved

![1715137923801](https://github.com/divelab/LECI/assets/169051868/2b1d9e9d-65e9-4b87-b798-6adb2e78fed8)

**Comment by CM-BF** [comment]
Given current provided information, it is hard to locate the problem. Would you mind to

1) Share the information of your system and conda environments?
2) Follow the installation instruction and the environment.yml?

Best

**Comment by depcco** [comment]
"Hi, I tried again and created a new conda environment. The code is running now. Thank you for your help."
