### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by depcco** [divelab/LECI#3]
@CM-BF 
I want to know if IDval and IDID are equivalent 。OOD val and OOD OOD are equivalent。The symbols are derived from the articles by GOOD and LECI.   I would be very grateful if you could answer me。
![image](https://github.com/divelab/LECI/assets/169051868/19138642-b66e-4abe-9a76-fd1796d03a79)
![image](https://github.com/divelab/LECI/assets/169051868/d6478b38-a3a3-4b2f-a6b1-da954bab58cd)

**Comment by depcco** [comment]
@CM-BF  Hello, when I tried to run TensorBoard while using code, I found that it did not show important parameters such as the saved learning rate curve. Do you know what could be causing this?
<img width="662" alt="1718065095270" src="https://github.com/divelab/LECI/assets/169051868/55540748-ed35-46b6-93c6-85d8d2b2ac2c">
<img width="332" alt="1718065114205" src="https://github.com/divelab/LECI/assets/169051868/effbaa24-a29a-4a56-bdb5-851f90a18593">

**Comment by CM-BF** [comment]
No and yes. ID val denotes the ID validated OOD result instead of the ID validated ID result (IDID).

**Comment by depcco** [comment]
thank you
