### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by depcco** [divelab/LECI#4]
@CM-BF
HI,I have a question about a piece of code. In GOOD\networks\models\GINS, there is code as shown in the image. Based on my understanding, self.convs.extend is used for the assignment operation, so the returned self.convs should be None. However, when I debugged it, it actually returned a specific network structure. Could you tell me why this happens? Thank you so much.
![image](https://github.com/user-attachments/assets/bf9f4929-f61a-45bf-852f-1ce6762c4379)

**Comment by CM-BF** [comment]
Hi @depcco,

The code logic here is to create a GIN with `num_layer` layers with different initial modules. The `.extend` operation is just to append the `num_layer - 1` GIN layers to the `convs` ModuleList. Note that `convs.append` only supports appending **one** module, while `convs.extend` supports merging with another list of modules. Please refer to the [official reference](https://pytorch.org/docs/stable/generated/torch.nn.ModuleList.html) for more details.

Thank you!

Best regards,
Shurui

**Comment by depcco** [comment]
thank you  Shurui。I think I've figured out this problem
