### ISSUE TITLE
Question about GOOD

### ISSUE THREAD

**Issue by vettelx** [divelab/LECI#6]
Great work! I’ve posted a similar question in GOOD repository, but I’d like to ask here as well to ensure it’s seen. Specifically, I’m curious about the differences between the GOOD-Motif dataset and the Spurious-Motif dataset. Additionally, I’d love to know how the visualizations for the datasets were created.

Best wishes,
Vettel

**Comment by CM-BF** [comment]
I have replied to you in GOOD repo. You may also find the CFP-Motif datasets in this work useful. : )

Best,
Shurui
